import { Router, type IRouter } from "express";
import healthRouter from "./health";
import eventsRouter from "./events";
import reportsRouter from "./reports";
import companiesRouter from "./companies";
import signalsRouter from "./signals";
import thoughtsRouter from "./thoughts";
import aiRouter from "./ai";
import settingsRouter from "./settings";
import stocksRouter from "./stocks";
import chatsRouter from "./chats";
import goalsRouter from "./goals";
import companyFactsRouter from "./companyFacts";
import roadmapsRouter from "./roadmaps";
import dailyBriefRouter from "./dailyBrief";
import queueRouter from "./queue";
import connectorsRouter from "./connectors";
import actionsRouter from "./actions";
import workflowsRouter from "./workflows";
import recapsRouter from "./recaps";
import attachmentsRouter from "./attachments";

const router: IRouter = Router();

router.use(healthRouter);
router.use(eventsRouter);
router.use(reportsRouter);
router.use(companiesRouter);
router.use(signalsRouter);
router.use(thoughtsRouter);
router.use(aiRouter);
router.use(settingsRouter);
router.use(stocksRouter);
router.use(chatsRouter);
router.use(goalsRouter);
router.use(companyFactsRouter);
router.use(roadmapsRouter);
router.use(dailyBriefRouter);
router.use(queueRouter);
router.use(connectorsRouter);
router.use(actionsRouter);
router.use(workflowsRouter);
router.use(recapsRouter);
router.use(attachmentsRouter);

export default router;
